---

- name: Configure iBGP on routers using OC NetworkInstance Model with YDK
  hosts: rtr_bgp
  connection: local
  gather_facts: no
  tasks:
    - name: configure BGP using YDK with GNMI
      config_bgp_oc_ydk:
        yang_repo_location: '{{ yang_repo_location }}'
        host: "{{ ansible_host }}"
        grpc_port: "{{ grpc_port }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        crud_op: "add"
        bgp_params: 
          vrf: 'default'
          as: "{{ local_as }}"
          router_id: "{{ loopback0_ip }}"
          peer-group-name: "IBGP"
          peer-as: "{{ hostvars[item].local_as }}"
          peer-group-local-address: "{{ loopback0_ip }}"
          neighbor: "{{ hostvars[item].loopback0_ip }}"
      with_items: "{{ groups['rtr_bgp'] }}"
      when: 
          - item != inventory_hostname
        # End of playbook

